export const en = {
  meta: {
    siteTitle: 'Liao Yi-Cheng | Personal Site',
  },
  nav: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    education: 'Education',
    certifications: 'Certifications',
    experience: 'Experience',
    contact: 'Contact',
  },
  home: {
    name: 'Liao Yi-Cheng',
    role: 'Undergraduate, National Yunlin University of Science and Technology',
    tagline: 'The programs we write are as spells fashioned from spirits out of our own minds.\n— "Structure and Interpretation of Computer Programs"',
    highlights: ['[Highlight 1, e.g. TOEIC 750]', '[Highlight 2, e.g. 2 projects]', '[Highlight 3, e.g. an internship]'],
    ctaProjects: 'View Projects',
    ctaAbout: 'About Me',
  },
  about: {
    title: 'About Me',
    intro: '[Self-introduction — TBD: 3-5 sentences on who you are, what you care about, what you are good at]',
    backgroundLabel: 'Education Background',
    background: [
      { period: '[Year range]', school: 'National Taipei University of Business', note: 'Five-Year Junior College' },
      { period: '[Year range, current]', school: 'National Yunlin University of Science and Technology', note: 'Two-Year Technical Program' },
    ],
    whyTechLabel: 'Why Tech',
    whyTech: '[Why you chose this field — TBD]',
    traitsLabel: 'Traits & Direction',
    traits: '[Personal traits and future direction — TBD]',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Each project includes planning diagrams and technical details — click through for the full story.',
    items: [
      { id: 'project-1', name: '[Project name 1]', summary: '[One line on the problem this solves]', tags: ['[Tech 1]', '[Tech 2]'] },
      { id: 'project-2', name: '[Project name 2]', summary: '[One line on the problem this solves]', tags: ['[Tech 1]', '[Tech 2]'] },
    ],
  },
  projectDetail: {
    backLabel: 'Back to Projects',
    motivationLabel: 'Motivation',
    approachLabel: 'Approach',
    techLabel: 'Tech Stack',
    roleLabel: 'My Role',
    resultLabel: 'Results',
    diagramsLabel: 'Planning Diagrams',
    linksLabel: 'Links',
    notFound: 'Project not found.',
    fallback: {
      motivation: '[Why this project — TBD]',
      approach: '[How it was built — TBD]',
      role: '[Your role on the project — TBD]',
      result: '[Concrete results, ideally with numbers — TBD]',
      diagrams: ['Architecture Diagram', 'ER Diagram', 'Flow Diagram'],
      github: '[GitHub link — TBD]',
      demo: '[Demo link — TBD]',
    },
  },
  education: {
    title: 'Education',
    timelineLabel: 'Timeline',
    statsLabel: 'Academic Record',
    gpaLabel: 'GPA / Percentile',
    gpa: '[GPA / percentile score — TBD]',
    rankLabel: 'Class / Department Rank',
    rank: '[Class / department rank — TBD]',
    coursesLabel: 'Relevant Coursework',
    courses: '[Relevant coursework — TBD]',
    awardsLabel: 'Scholarships & Honors',
    awards: '[Dean’s list or scholarships — TBD]',
    privacyNote: 'A full transcript will be provided separately in the application. Only highlights and relevant courses are shown here.',
  },
  certifications: {
    title: 'Certifications & Skills',
    certsLabel: 'Certifications',
    certs: [{ name: '[Certificate name]', issuer: '[Issuing organization]', date: '[Date obtained]' }],
    skillsLabel: 'Skills',
    skillCategoryLabels: {
      languages: 'Languages',
      backend: 'Backend',
      database: 'Database',
      cloud: 'Cloud',
      tools: 'Tools',
    },
    skills: {
      languages: ['[Language]'],
      backend: ['[Backend tech]'],
      database: ['[Database]'],
      cloud: ['[Cloud service]'],
      tools: ['[Tools]'],
    },
  },
  experience: {
    title: 'Experience',
    subtitle: 'Internships, competitions, capstones, clubs, volunteering, exchange — this is where you stand out.',
    items: [
      { title: '[Experience title, e.g. Internship at OO]', period: '[Time range]', description: '[What you did + what it produced — TBD]' },
    ],
  },
  contact: {
    title: 'Contact',
    intro: 'Feel free to reach out through any of the channels below.',
    email: 'easonliao0820@gmail.com',
    github: '[GitHub link — TBD]',
    linkedin: '[LinkedIn link — TBD]',
    resumeLabel: 'Download Resume (PDF)',
    resumeHref: '#',
  },
}
