export const en = {
  meta: {
    siteTitle: 'Liao Yi-Cheng | Personal Site',
  },
  nav: {
    home: 'Home',
    about: 'About',
    projects: 'Projects',
    education: 'Education',
    certifications: 'Certifications',
    experience: 'Experience',
    contact: 'Contact',
  },
  home: {
    name: 'Liao Yi-Cheng',
    role: 'Undergraduate, National Yunlin University of Science and Technology',
    tagline: 'The programs we write are as spells fashioned from spirits out of our own minds.\n— "Structure and Interpretation of Computer Programs"',
    highlights: ['[Highlight 1, e.g. TOEIC 750]', '[Highlight 2, e.g. 2 projects]', '[Highlight 3, e.g. an internship]'],
    ctaProjects: 'View Projects',
    ctaAbout: 'About Me',
  },
  about: {
    title: 'About Me',
    intro: '[Self-introduction — TBD: 3-5 sentences on who you are, what you care about, what you are good at]',
    backgroundLabel: 'Education Background',
    background: [
      { period: '2020–2025', school: 'National Taipei University of Business', note: 'Five-Year Junior College' },
      { period: '2025–Present', school: 'National Yunlin University of Science and Technology', note: 'Two-Year Technical Program' },
    ],
    whyTechLabel: 'Why Tech',
    whyTech: '[Why you chose this field — TBD]',
    traitsLabel: 'Traits & Direction',
    traits: '[Personal traits and future direction — TBD]',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Each project includes planning diagrams and technical details — click through for the full story.',
    items: [
      { id: 'project-1', name: '[Project name 1]', summary: '[One line on the problem this solves]', tags: ['[Tech 1]', '[Tech 2]'] },
      { id: 'project-2', name: '[Project name 2]', summary: '[One line on the problem this solves]', tags: ['[Tech 1]', '[Tech 2]'] },
      {
        id: 'lvren',
        name: 'LǚRén (履人)',
        summary: 'Software that helps interviewers quickly find an applicant\'s name and related content within a large pile of paper application materials.',
        tags: ['React', 'SCSS', 'Flask', 'AI'],
        motivation:
          'As we approached graduation and started preparing our own application review materials, we noticed how reviewers face a huge volume of paper applications from every direction, making it a real challenge for any one applicant to stand out. At the same time, teachers conducting interviews struggle to quickly locate an applicant\'s name and related information. We realized that the core value of programming is helping people complete tasks more efficiently within limited time, so we set out to build "LǚRén" to help interviewers quickly find applicant information during the interview process. Entry for the 2024 National Collegiate Industry-Academia Innovation Competition, AI & Applications Track.',
        approach: 'Built the front-end UI with React and SCSS, with a Flask back end providing the API, wired together with the [core recognition/matching logic — TBD].',
        role: 'Front-end development, plus integrating all the features end-to-end.',
        result: 'Advanced to the finals and received an Honorable Mention.',
        demo: '[Demo link — TBD]',
        github: '[GitHub link — TBD]',
        photo: '/experience/2024-national-innovation/photo.png',
        documents: [
          { href: '/experience/2024-national-innovation/certificate-of-selection.png', label: 'View Selection Certificate' },
          { href: '/experience/2024-national-innovation/certificate-of-merit.png', label: 'View Merit Certificate' },
        ],
      },
      {
        id: 'ntub-smart-key-cabinet',
        name: 'NTUB Smart Key Cabinet System',
        summary: 'A smart key cabinet management system built by the Business Intelligence Research Center, front-end development.',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: 'One of the Practical Talent Excellence Program (Business Intelligence Research Center) projects, used to manage the campus key checkout process.',
        approach: 'Built the front end with HTML, SCSS, and React, with ESLint for code quality, wired to the management functionality provided by the center\'s back end.',
        role: 'Front-end development.',
        result: 'The system is live and in active use on campus.',
        demo: 'https://keycabinet.ntubimdbirc.tw/',
        github: '(Internal project, no public repository)',
      },
      {
        id: 'ntub-tactl-website',
        name: 'Teaching and Learning Center Website',
        summary: 'Official website of the Teaching and Learning Center at National Taipei University of Business, front-end development.',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: 'One of the Practical Talent Excellence Program (Business Intelligence Research Center) projects, serving as the Teaching and Learning Center\'s public website.',
        approach: 'Built the front end with HTML, SCSS, and React, with ESLint for code quality.',
        role: 'Front-end development.',
        result: 'The site is live, used by faculty and students to access Teaching and Learning Center information.',
        demo: 'https://tactl.ntub.edu.tw/',
        github: '(Internal project, no public repository)',
      },
      {
        id: 'ntub-ta-portal',
        name: 'NTUB Teaching Assistant Portal',
        summary: 'A portal site providing information for teaching assistants, front-end development.',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: 'One of the Practical Talent Excellence Program (Business Intelligence Research Center) projects, consolidating teaching-assistant information.',
        approach: 'Built the front end with HTML, SCSS, and React, with ESLint for code quality.',
        role: 'Front-end development.',
        result: 'The site is live and used by teaching assistants and instructors.',
        demo: 'https://tactl.ntub.edu.tw/landing',
        github: '(Internal project, no public repository)',
      },
      {
        id: 'ils-smart-living-space',
        name: 'Ministry of the Interior — Smart Living Space Site',
        summary: 'A showcase site for the Architecture and Building Research Institute\'s Smart Living Space, front-end development.',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: 'One of the Practical Talent Excellence Program (Business Intelligence Research Center) projects, commissioned by a government agency as a public showcase for the Smart Living Space.',
        approach: 'Built the front end with HTML, SCSS, and React, with ESLint for code quality.',
        role: 'Front-end development.',
        result: 'The site is live, helping the public learn about the Smart Living Space initiative.',
        demo: 'https://www.ils.org.tw/',
        github: '(Internal project, no public repository)',
      },
    ],
  },
  projectDetail: {
    backLabel: 'Back to Projects',
    motivationLabel: 'Motivation',
    approachLabel: 'Approach',
    techLabel: 'Tech Stack',
    roleLabel: 'My Role',
    resultLabel: 'Results',
    diagramsLabel: 'Planning Diagrams',
    linksLabel: 'Links',
    documentsLabel: 'Related Certificates',
    notFound: 'Project not found.',
    fallback: {
      motivation: '[Why this project — TBD]',
      approach: '[How it was built — TBD]',
      role: '[Your role on the project — TBD]',
      result: '[Concrete results, ideally with numbers — TBD]',
      diagrams: ['Architecture Diagram', 'ER Diagram', 'Flow Diagram'],
      github: '[GitHub link — TBD]',
      demo: '[Demo link — TBD]',
    },
  },
  education: {
    title: 'Education',
    timelineLabel: 'Timeline',
    statsLabel: 'Academic Record',
    gpaLabel: 'GPA / Percentile',
    gpa: '[GPA / percentile score — TBD]',
    rankLabel: 'Class / Department Rank',
    rank: '[Class / department rank — TBD]',
    coursesLabel: 'Relevant Coursework',
    courses: '[Relevant coursework — TBD]',
    awardsLabel: 'Scholarships & Honors',
    awards: '[Dean’s list or scholarships — TBD]',
    privacyNote: 'A full transcript will be provided separately in the application. Only highlights and relevant courses are shown here.',
  },
  certifications: {
    title: 'Certifications & Skills',
    certsLabel: 'Certifications',
    certs: [{ name: '[Certificate name]', issuer: '[Issuing organization]', date: '[Date obtained]' }],
    skillsLabel: 'Skills',
    skillCategoryLabels: {
      frontend: 'Frontend',
      backend: 'Backend',
      database: 'Database',
      cloud: 'Cloud',
      tools: 'Tools',
    },
    skills: {
      frontend: ['HTML', 'CSS', 'JavaScript', 'SCSS', 'React', 'Next.js'],
      backend: ['Node.js', 'PHP', 'Python', 'Java'],
      database: ['[Database]'],
      cloud: ['[Cloud service]'],
      tools: ['[Tools]'],
    },
  },
  experience: {
    title: 'Experience',
    subtitle: 'Internships, competitions, capstones, clubs, volunteering, exchange — this is where you stand out.',
    filterAll: 'All',
    categoryLabels: {
      competition: 'Competitions',
      teaching: 'Teaching',
      leadership: 'Leadership',
      internship: 'Internship',
    },
    items: [
      {
        title: '2023 Information Month Information Application Skills Competition (Digital Content & Software Application Contest) — Python Track',
        category: 'competition',
        period: 'Oct–Nov 2023',
        description: 'Competed in the Python track; placed 3rd in the Northern Region team category and 5th nationwide (participation certificate and award certificates on file).',
        photo: '/experience/2023-info-month-python/photo.png',
        documents: [
          { href: '/experience/2023-info-month-python/participation-certificate.png', label: 'View Participation Certificate' },
          { href: '/experience/2023-info-month-python/award-certificate-north.png', label: 'View Northern Region Award Certificate' },
          { href: '/experience/2023-info-month-python/award-certificate-national.png', label: 'View National Award Certificate' },
        ],
      },
      {
        title: '2022 Northern Region Collegiate Programming Contest — Beginner Division',
        category: 'competition',
        period: 'Jun 2022',
        description: 'Competed in the beginner division (participation certificate on file).',
        photo: '/experience/2022-northern-region-contest/photo.png',
        documents: [{ href: '/experience/2022-northern-region-contest/participation-certificate.png', label: 'View Participation Certificate' }],
      },
      {
        title: '2024 Northern Seven Universities Alliance Programming Contest — Beginner Division',
        category: 'competition',
        period: 'May 2024',
        description: 'Solved 9 problems and received the Outstanding Performance Award (participation certificate and award certificate on file).',
        photo: '/experience/2024-seven-university-alliance/photo.png',
        documents: [
          { href: '/experience/2024-seven-university-alliance/participation-certificate.png', label: 'View Participation Certificate' },
          { href: '/experience/2024-seven-university-alliance/award-certificate.png', label: 'View Outstanding Performance Award' },
        ],
      },
      {
        title: '2024 National Collegiate Industry-Academia Innovation Competition — AI & Applications Track',
        category: 'competition',
        period: 'Dec 2024',
        description: 'Project "LǚRén" (履人) advanced to the finals and received an Honorable Mention (selection certificate and award certificate on file).',
        photo: '/experience/2024-national-innovation/photo.png',
        documents: [
          { href: '/experience/2024-national-innovation/certificate-of-selection.png', label: 'View Selection Certificate' },
          { href: '/experience/2024-national-innovation/certificate-of-merit.png', label: 'View Merit Certificate' },
        ],
      },
      {
        title: 'Practical Talent Excellence Program — Business Intelligence Research Center (National Taipei University of Business)',
        category: 'teaching',
        period: '[TBD: academic year/semester attended]',
        description:
          'Took part in the Business Intelligence Research Center\'s hands-on training program as a front-end developer and instructor. In a 16-week full-stack bootcamp, guided by the center\'s assistant engineer, taught fellow participants (open to students and outsiders) to build web pages from scratch with HTML, CSS, and React. Also mentored incoming students on the front end as part of the center\'s recruiting and knowledge-transfer program. Projects built during this program are listed on the Projects page (some screens/URLs are withheld due to internal domains or confidentiality).',
        documents: [{ href: 'https://www.ntubimdbirc.tw/', label: 'Business Intelligence Research Center' }],
      },
      {
        title: 'Mini Voice Player (MVP Bootcamp) Teaching Activity',
        category: 'teaching',
        period: 'Jan 2024 (1/22, 1/29)',
        description: 'Led teaching activities at the MVP Bootcamp, running interactive programming/voice-related sessions for elementary and middle school students.',
        documents: [{ href: 'https://www.learnnest.com.tw/', label: 'Bootcamp Website' }],
      },
      {
        title: 'Class Representative, Fall Semester 2024 (113 Academic Year)',
        category: 'leadership',
        period: 'Fall 2024 (Sep 2024–Jan 2025)',
        description:
          'Served as class representative for the Department of Information Management, Five-Year Junior College Division, National Taipei University of Business, Fall Semester of the 113 academic year. Certificate issued by the Student Affairs Office, Student Guidance Section (Certificate No. 北商大學(生)字第11400505號, issued March 20, 2025).',
      },
      {
        title: '[Experience title, e.g. Internship at OO]',
        category: 'internship',
        period: '[Time range]',
        description: '[What you did + what it produced — TBD]',
      },
    ],
  },
  contact: {
    title: 'Contact',
    intro: 'Feel free to reach out through any of the channels below.',
    email: 'easonliao0820@gmail.com',
    github: '[GitHub link — TBD]',
    linkedin: '[LinkedIn link — TBD]',
    resumeLabel: 'Download Resume (PDF)',
    resumeHref: '#',
  },
}
