export const zh = {
  meta: {
    siteTitle: '廖翊丞｜個人網站',
  },
  nav: {
    home: '首頁',
    about: '關於我',
    projects: '作品集',
    education: '學歷與成績',
    certifications: '證照與技能',
    experience: '特殊經驗',
    contact: '聯絡',
  },
  home: {
    name: '廖翊丞',
    role: '國立雲林科技大學 二技在學',
    tagline: '我們寫下的程式，就像是由我們心中的靈魂所煉製而成的咒語。\n——《計算機程序的構造和解釋》',
    highlights: ['〔亮點數字 1，如：多益 750〕', '〔亮點數字 2，如：2 個專案作品〕', '〔亮點數字 3，如：一段實習經驗〕'],
    ctaProjects: '瀏覽作品集',
    ctaAbout: '認識我',
  },
  about: {
    title: '關於我',
    intro: '〔自我介紹段落 — 待補：用 3–5 句話說明你是誰、關注什麼、擅長什麼〕',
    backgroundLabel: '求學背景',
    background: [
      { period: '2020-2025', school: '國立臺北商業大學', note: '五年制專科部（五專）' },
      { period: '2025-現在', school: '國立雲林科技大學', note: '二年制技術系班（二技）' },
    ],
    whyTechLabel: '為什麼走資訊',
    whyTech: '〔為什麼走資訊這條路 — 待補〕',
    traitsLabel: '個人特質與未來方向',
    traits: '〔個人特質與未來方向 — 待補〕',
  },
  projects: {
    title: '作品集',
    subtitle: '每個專案都附上規劃圖與技術細節，點進去看完整故事。',
    items: [
      {
        id: 'project-1',
        name: '〔專案名稱一〕',
        summary: '〔一句話說明這個專案解決什麼問題〕',
        tags: ['〔技術一〕', '〔技術二〕'],
      },
      {
        id: 'project-2',
        name: '〔專案名稱二〕',
        summary: '〔一句話說明這個專案解決什麼問題〕',
        tags: ['〔技術一〕', '〔技術二〕'],
      },
    ],
  },
  projectDetail: {
    backLabel: '返回作品集',
    motivationLabel: '動機',
    approachLabel: '做法',
    techLabel: '技術',
    roleLabel: '我的角色',
    resultLabel: '成果',
    diagramsLabel: '規劃圖',
    linksLabel: '連結',
    notFound: '找不到這個專案。',
    fallback: {
      motivation: '〔為什麼做這個專案 — 待補〕',
      approach: '〔怎麼做的 — 待補〕',
      role: '〔你在專案中的角色 — 待補〕',
      result: '〔具體成果，盡量有數字 — 待補〕',
      diagrams: ['架構圖', 'ER 圖', '流程圖'],
      github: '〔GitHub 連結 — 待補〕',
      demo: '〔Demo 連結 — 待補〕',
    },
  },
  education: {
    title: '學歷與成績',
    timelineLabel: '學歷',
    statsLabel: '在校成績',
    gpaLabel: 'GPA / 百分制',
    gpa: '〔GPA / 百分制成績 — 待補〕',
    rankLabel: '班排 / 系排',
    rank: '〔班排 / 系排 — 待補〕',
    coursesLabel: '相關修課',
    courses: '〔相關修課列表 — 待補〕',
    awardsLabel: '獎學金與書卷獎',
    awards: '〔書卷獎或獎學金 — 待補〕',
    privacyNote: '完整成績單將於推甄資料中另行提供，此處僅列亮點與相關科目。',
  },
  certifications: {
    title: '證照與技能',
    certsLabel: '證照',
    certs: [{ name: '〔證照名稱〕', issuer: '〔發證單位〕', date: '〔取得日期〕' }],
    skillsLabel: '技能',
    skillCategoryLabels: {
      frontend: '前端',
      backend: '後端',
      database: '資料庫',
      cloud: '雲端',
      tools: '工具',
    },
    skills: {
      frontend: ['HTML', 'CSS', 'JavaScript', 'SCSS', 'React', 'Next.js'],
      backend: ['Node.js', 'PHP', 'Python', 'Java'],
      database: ['〔資料庫〕'],
      cloud: ['〔雲端服務〕'],
      tools: ['〔工具〕'],
    },
  },
  experience: {
    title: '特殊經驗',
    subtitle: '實習、競賽、專題、社團、志工、交換 — 這裡是拉開差距的地方。',
    items: [
      {
        title: '〔全國大專校院資訊應用服務創新競賽 — 網頁應用組〕',
        period: '〔2025 年〕',
        description: '〔與隊友合作開發解決〔某個問題〕的網頁應用，負責前端介面與資料視覺化，最終獲得〔佳作／第 X 名〕〕',
        photo: '/experience/competition-1.jpg',
        documentHref: '/experience/competition-1.pdf',
        documentLabel: '查看得獎證明',
      },
      {
        title: '〔校內程式設計競賽〕',
        period: '〔2024 年〕',
        description: '〔在時限內完成〔題數〕道演算法題目，獲得〔名次／獎項〕〕',
      },
      {
        title: '〔OO 黑客松 Hackathon〕',
        period: '〔2024 年〕',
        description: '〔48 小時內與團隊打造聚焦於〔主題〕的原型專案，榮獲〔獎項〕〕',
      },
      {
        title: '〔經驗標題，如：OO 公司實習〕',
        period: '〔時間區間〕',
        description: '〔你做了什麼 + 帶來什麼成果 — 待補〕',
      },
    ],
  },
  contact: {
    title: '聯絡',
    intro: '歡迎透過以下方式聯絡我。',
    email: 'easonliao0820@gmail.com',
    github: '〔GitHub 連結 — 待補〕',
    linkedin: '〔LinkedIn 連結 — 待補〕',
    resumeLabel: '下載履歷 PDF',
    resumeHref: '#',
  },
}
