export const zh = {
  meta: {
    siteTitle: '廖翊丞｜個人網站',
  },
  nav: {
    home: '首頁',
    about: '關於我',
    projects: '作品集',
    education: '學歷與成績',
    certifications: '證照與技能',
    experience: '特殊經驗',
    contact: '聯絡',
  },
  home: {
    name: '廖翊丞',
    role: '國立雲林科技大學 二技在學',
    tagline: '我們寫下的程式，就像是由我們心中的靈魂所煉製而成的咒語。\n——《計算機程序的構造和解釋》',
    highlights: ['〔亮點數字 1，如：多益 750〕', '〔亮點數字 2，如：2 個專案作品〕', '〔亮點數字 3，如：一段實習經驗〕'],
    ctaProjects: '瀏覽作品集',
    ctaAbout: '認識我',
  },
  about: {
    title: '關於我',
    intro: '〔自我介紹段落 — 待補：用 3–5 句話說明你是誰、關注什麼、擅長什麼〕',
    backgroundLabel: '求學背景',
    background: [
      { period: '2020-2025', school: '國立臺北商業大學', note: '五年制專科部（五專）' },
      { period: '2025-現在', school: '國立雲林科技大學', note: '二年制技術系班（二技）' },
    ],
    whyTechLabel: '為什麼走資訊',
    whyTech: '〔為什麼走資訊這條路 — 待補〕',
    traitsLabel: '個人特質與未來方向',
    traits: '〔個人特質與未來方向 — 待補〕',
  },
  projects: {
    title: '作品集',
    subtitle: '每個專案都附上規劃圖與技術細節，點進去看完整故事。',
    items: [
      {
        id: 'project-1',
        name: '〔專案名稱一〕',
        summary: '〔一句話說明這個專案解決什麼問題〕',
        tags: ['〔技術一〕', '〔技術二〕'],
      },
      {
        id: 'project-2',
        name: '〔專案名稱二〕',
        summary: '〔一句話說明這個專案解決什麼問題〕',
        tags: ['〔技術一〕', '〔技術二〕'],
      },
      {
        id: 'lvren',
        name: '履人（LǚRén）',
        summary: '幫助面試官在大量書面申請資料中，快速找到申請者姓名與相關內容的軟體。',
        tags: ['React', 'SCSS', 'Flask', '人工智慧'],
        motivation:
          '專四即將畢業、開始準備書審資料時，我們注意到評審委員要面對大量四面八方的書面申請資料，如何在眾多申請者中脫穎而出是一大課題；同時，老師們在面試過程中，也面臨如何有效率地找到申請者姓名與相關資料的挑戰。我們意識到程式設計的核心價值，就是幫助人們在有限時間內更有效率地完成任務，因此規劃開發「履人」，協助老師在面試過程中快速找到申請者的資料。2024全國大專院校產學創新實作競賽（人工智慧及其應用組）參賽作品。',
        approach: '前端以 React、SCSS 打造使用者介面，後端以 Flask 提供 API，串接前後端與〔核心辨識／比對邏輯 — 待補〕功能。',
        role: '負責前端開發，以及全部功能的串接整合。',
        result: '入圍決賽，最終獲得佳作。',
        demo: '〔Demo 連結 — 待補〕',
        github: '〔GitHub 連結 — 待補〕',
        photo: '/experience/2024-national-innovation/photo.png',
        documents: [
          { href: '/experience/2024-national-innovation/certificate-of-selection.png', label: '查看入選證明' },
          { href: '/experience/2024-national-innovation/certificate-of-merit.png', label: '查看佳作獎狀' },
        ],
      },
      {
        id: 'ntub-smart-key-cabinet',
        name: '北商智慧鑰匙櫃系統',
        summary: '商業智慧研究中心開發的智慧鑰匙櫃管理系統，負責前端頁面開發。',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: '實用人才拔尖計畫（商業智慧研究中心）培育專案之一，用於管理校內鑰匙借還流程。',
        approach: '以 HTML、SCSS、React 打造前端介面，並用 ESLint 檢查程式碼品質，串接中心後端提供的管理功能。',
        role: '負責前端頁面開發。',
        result: '系統已上線，供校內使用中。',
        demo: 'https://keycabinet.ntubimdbirc.tw/',
        github: '（校內專案，無公開原始碼）',
      },
      {
        id: 'ntub-tactl-website',
        name: '教學發展中心網站',
        summary: '國立臺北商業大學教學發展中心官方網站，負責前端頁面開發。',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: '實用人才拔尖計畫（商業智慧研究中心）培育專案之一，作為教學發展中心的對外官方網站。',
        approach: '以 HTML、SCSS、React 打造前端介面，並用 ESLint 檢查程式碼品質。',
        role: '負責前端頁面開發。',
        result: '網站已上線，供全校師生查閱教學發展中心資訊。',
        demo: 'https://tactl.ntub.edu.tw/',
        github: '（校內專案，無公開原始碼）',
      },
      {
        id: 'ntub-ta-portal',
        name: '臺北商業大學教學助理專區',
        summary: '提供教學助理相關資訊的專區網站，負責前端頁面開發。',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: '實用人才拔尖計畫（商業智慧研究中心）培育專案之一，整合教學助理相關資訊。',
        approach: '以 HTML、SCSS、React 打造前端介面，並用 ESLint 檢查程式碼品質。',
        role: '負責前端頁面開發。',
        result: '網站已上線，供教學助理與教師查閱使用。',
        demo: 'https://tactl.ntub.edu.tw/landing',
        github: '（校內專案，無公開原始碼）',
      },
      {
        id: 'ils-smart-living-space',
        name: '內政部建築研究所－智慧化居住空間前台網站',
        summary: '內政部建築研究所智慧化居住空間展示網站，負責前端頁面開發。',
        tags: ['HTML', 'SCSS', 'React', 'ESLint'],
        motivation: '實用人才拔尖計畫（商業智慧研究中心）承接的政府單位委託專案，作為智慧化居住空間的對外展示網站。',
        approach: '以 HTML、SCSS、React 打造前端介面，並用 ESLint 檢查程式碼品質。',
        role: '負責前端頁面開發。',
        result: '網站已上線，供大眾了解智慧化居住空間相關資訊。',
        demo: 'https://www.ils.org.tw/',
        github: '（校內專案，無公開原始碼）',
      },
    ],
  },
  projectDetail: {
    backLabel: '返回作品集',
    motivationLabel: '動機',
    approachLabel: '做法',
    techLabel: '技術',
    roleLabel: '我的角色',
    resultLabel: '成果',
    diagramsLabel: '規劃圖',
    linksLabel: '連結',
    documentsLabel: '相關證明',
    notFound: '找不到這個專案。',
    fallback: {
      motivation: '〔為什麼做這個專案 — 待補〕',
      approach: '〔怎麼做的 — 待補〕',
      role: '〔你在專案中的角色 — 待補〕',
      result: '〔具體成果，盡量有數字 — 待補〕',
      diagrams: ['架構圖', 'ER 圖', '流程圖'],
      github: '〔GitHub 連結 — 待補〕',
      demo: '〔Demo 連結 — 待補〕',
    },
  },
  education: {
    title: '學歷與成績',
    timelineLabel: '學歷',
    statsLabel: '在校成績',
    gpaLabel: 'GPA / 百分制',
    gpa: '〔GPA / 百分制成績 — 待補〕',
    rankLabel: '班排 / 系排',
    rank: '〔班排 / 系排 — 待補〕',
    coursesLabel: '相關修課',
    courses: '〔相關修課列表 — 待補〕',
    awardsLabel: '獎學金與書卷獎',
    awards: '〔書卷獎或獎學金 — 待補〕',
    privacyNote: '完整成績單將於推甄資料中另行提供，此處僅列亮點與相關科目。',
  },
  certifications: {
    title: '證照與技能',
    certsLabel: '證照',
    certs: [{ name: '〔證照名稱〕', issuer: '〔發證單位〕', date: '〔取得日期〕' }],
    skillsLabel: '技能',
    skillCategoryLabels: {
      frontend: '前端',
      backend: '後端',
      database: '資料庫',
      cloud: '雲端',
      tools: '工具',
    },
    skills: {
      frontend: ['HTML', 'CSS', 'JavaScript', 'SCSS', 'React', 'Next.js'],
      backend: ['Node.js', 'PHP', 'Python', 'Java'],
      database: ['〔資料庫〕'],
      cloud: ['〔雲端服務〕'],
      tools: ['〔工具〕'],
    },
  },
  experience: {
    title: '特殊經驗',
    subtitle: '實習、競賽、專題、社團、志工、交換 — 這裡是拉開差距的地方。',
    filterAll: '全部',
    categoryLabels: {
      competition: '競賽',
      teaching: '教學',
      leadership: '幹部',
      internship: '實習',
    },
    items: [
      {
        title: '112資訊月資訊應用技能競賽（數位內容軟體應用大賽）— 程式語言 Python 組',
        category: 'competition',
        period: '2023年10–11月',
        description: '參加程式語言 Python 組競賽，獲得北區團體組第三名、全國團體組第五名（含參賽證明與獎狀）。',
        photo: '/experience/2023-info-month-python/photo.png',
        documents: [
          { href: '/experience/2023-info-month-python/participation-certificate.png', label: '查看參賽證明' },
          { href: '/experience/2023-info-month-python/award-certificate-north.png', label: '查看北區團體組獎狀' },
          { href: '/experience/2023-info-month-python/award-certificate-national.png', label: '查看全國團體組獎狀' },
        ],
      },
      {
        title: '2022北區大專校院程式設計競賽 — 初級組',
        category: 'competition',
        period: '2022年6月',
        description: '參加初級組程式設計競賽（含參賽證明）。',
        photo: '/experience/2022-northern-region-contest/photo.png',
        documents: [{ href: '/experience/2022-northern-region-contest/participation-certificate.png', label: '查看參賽證明' }],
      },
      {
        title: '2024北區七校聯盟程式設計競賽 — 初級組',
        category: 'competition',
        period: '2024年5月',
        description: '共解 9 題，獲得表現卓越獎（含參賽證明與獎狀）。',
        photo: '/experience/2024-seven-university-alliance/photo.png',
        documents: [
          { href: '/experience/2024-seven-university-alliance/participation-certificate.png', label: '查看參賽證明' },
          { href: '/experience/2024-seven-university-alliance/award-certificate.png', label: '查看表現卓越獎狀' },
        ],
      },
      {
        title: '2024全國大專院校產學創新實作競賽 — 人工智慧及其應用組',
        category: 'competition',
        period: '2024年12月',
        description: '作品「履人」入圍決賽，最終獲得佳作（含入選證明與獎狀）。',
        photo: '/experience/2024-national-innovation/photo.png',
        documents: [
          { href: '/experience/2024-national-innovation/certificate-of-selection.png', label: '查看入選證明' },
          { href: '/experience/2024-national-innovation/certificate-of-merit.png', label: '查看佳作獎狀' },
        ],
      },
      {
        title: '實用人才拔尖計畫 — 商業智慧研究中心（國立臺北商業大學）',
        category: 'teaching',
        period: '〔待補：參與學年/學期〕',
        description:
          '參與商業智慧研究中心的實務培育計畫，負責前端開發與教學。於 16 週全端體驗營中，在中心助理工程師帶領下指導校內外學員以 HTML、CSS、React 從零架設網頁；並於中心新生招募與傳承中，擔任學弟妹的前端教學與指導。期間參與的專案作品請見「作品集」頁（部分畫面／網址因內部網域或保密考量未列出）。',
        documents: [{ href: 'https://www.ntubimdbirc.tw/', label: '商業智慧研究中心官網' }],
      },
      {
        title: 'Mini Voice Player（MVP 養成營）教學活動',
        category: 'teaching',
        period: '2024年1月（1/22、1/29）',
        description: '於 MVP 養成營帶領教學活動，與國小／國中學童進行程式與語音相關的互動教學。',
        documents: [{ href: 'https://www.learnnest.com.tw/', label: '養成營官網' }],
      },
      {
        title: '113學年度第1學期 班代（班級幹部）',
        category: 'leadership',
        period: '113學年度第1學期（2024年9月–2025年1月）',
        description:
          '擔任國立臺北商業大學專科部五專資訊管理科 113 學年度第1學期班代，經學務處生輔組核發幹部證明（證明字號：北商大學(生)字第11400505號，中華民國114年3月20日核發）。',
      },
      {
        title: '〔經驗標題，如：OO 公司實習〕',
        category: 'internship',
        period: '〔時間區間〕',
        description: '〔你做了什麼 + 帶來什麼成果 — 待補〕',
      },
    ],
  },
  contact: {
    title: '聯絡',
    intro: '歡迎透過以下方式聯絡我。',
    email: 'easonliao0820@gmail.com',
    github: '〔GitHub 連結 — 待補〕',
    linkedin: '〔LinkedIn 連結 — 待補〕',
    resumeLabel: '下載履歷 PDF',
    resumeHref: '#',
  },
}
